name: XCS236_CUDA
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - cloudpickle=3.0.0
  - cycler=0.11.0
  - h5py=3.12.1
  - lockfile=0.12.2
  - opt-einsum=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pickleshare=0.7.5
  - python-dateutil=2.9.0.post0
  - requests=2.32.3
  - scipy=1.13.1
  - six=1.16.0
  - scikit-learn=1.5.2
  - tensorboard=2.17.0
  - pytest=7.4.4
  - imageio=2.33.1
  - svglib=1.5.1
  - googledrivedownloader=0.4
  - matplotlib=3.9.2
  - pyyaml=6.0.2
  - tqdm=4.66.5
  - regex=2024.11.6
  - thefuzz=0.22.1
  - rapidfuzz=3.5.2
  - seaborn=0.13.2
  - pip=24.2
  - pip:
    - timeout_decorator==0.5.0
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.5.1+cu121
    - "--find-links https://download.pytorch.org/whl/torchvision/"
    - torchvision==0.20.1+cu121
    - rouge-score==0.1.2
    # Manage the below packages over pip to avoid segmentation fault in transformers on Mac
    - huggingface-hub==0.27.1
    - transformers==4.48.1
    - datasets==3.2.0
    - numpy==2.0.2
